
# File: .github/workflows/workflow.yml

on:
  workflow_dispatch:

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

        run: |
          # Your Azure CLI commands to create a resource
          az group create --name MyResourceGroup --location eastus
          az storage account create --name mystorageaccount --resource-group MyResourceGroup --location eastus --sku Standard_LRS
